# Generated by Django 3.2.19 on 2023-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Введите язык книги', max_length=100, verbose_name='Язык'),
        ),
    ]
